arm_hw:
  bus:
    - can0
    - can1
  loop_frequency: 1000
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  actuators:
    active_joint1_motor:
      bus: can0
      id: 0x201
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    active_joint2_motor:
      bus: can0
      id: 0x202
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    active_joint3_motor:
      bus: can0
      id: 0x203
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100

    parallel_up_a_joint1_motor:
      bus: can1
      id: 0x001
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_up_b_joint1_motor:
      bus: can1
      id: 0x002
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_b_joint1_motor:
      bus: can1
      id: 0x003
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_a_joint1_motor:
      bus: can1
      id: 0x004
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100

    parallel_up_a_joint2_motor:
      bus: can1
      id: 0x005
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_up_b_joint2_motor:
      bus: can1
      id: 0x006
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_b_joint2_motor:
      bus: can1
      id: 0x007
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_a_joint2_motor:
      bus: can1
      id: 0x008
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100

    parallel_up_a_joint3_motor:
      bus: can1
      id: 0x009
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_up_b_joint3_motor:
      bus: can1
      id: 0x010
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_b_joint3_motor:
      bus: can1
      id: 0x011
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
    parallel_down_a_joint3_motor:
      bus: can1
      id: 0x012
      type: rm_2006
      act_offset: 0.
      lp_cutoff_frequency: 100
#    EE_joint_motor:
#      bus: can0
#      id: 0x004
#      type: dm4310
#      act_offset: 0.