arm_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 1000
      d: 1
      i: 50
      i_clamp: 10
    joint2:
      p: 1000
      d: 10
      i: 50
      i_clamp: 10
    joint3:
      p: 1000
      d: 10
      i: 50
      i_clamp: 10
    joint4:
      p: 500
      d: 1
      i: 10
      i_clamp: 10
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 10
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 10